// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJam9TeXvOAp3lomlVFk0w0gIyRpwVg_M',
    appId: '1:1017501524522:web:729908c71e6a15de935953',
    messagingSenderId: '1017501524522',
    projectId: 'forge-f9e44',
    authDomain: 'forge-f9e44.firebaseapp.com',
    storageBucket: 'forge-f9e44.firebasestorage.app',
    measurementId: 'G-WYP1RM70P7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOFs4xmGz6QFFQ3HxHh5Acqt0szZRgSus',
    appId: '1:1017501524522:ios:bb9d2b8cebcb3d93935953',
    messagingSenderId: '1017501524522',
    projectId: 'forge-f9e44',
    storageBucket: 'forge-f9e44.firebasestorage.app',
    iosBundleId: 'com.lifesync.forge',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOFs4xmGz6QFFQ3HxHh5Acqt0szZRgSus',
    appId: '1:1017501524522:ios:bb9d2b8cebcb3d93935953',
    messagingSenderId: '1017501524522',
    projectId: 'forge-f9e44',
    storageBucket: 'forge-f9e44.firebasestorage.app',
    iosBundleId: 'com.lifesync.forge',
  );
}
